### PR TITLE
Added Issue Credential v1.0 and Present Proof v1.0 in supported protocols

### PR DESCRIPTION
**Pull request by lalc**

### CODE REVIEW

**Comment by cre8** [comment]
@lalc do you have a link to specification for the issuance protocol?

**Comment by lalc** [comment]
> @lalc do you have a link to specification for the issuance protocol?

Here you go: https://github.com/hyperledger/aries-rfcs/blob/main/features/0036-issue-credential/README.md

**Comment by cre8** [comment]
> > @lalc do you have a link to specification for the issuance protocol?
> 
> Here you go: https://github.com/hyperledger/aries-rfcs/blob/main/features/0036-issue-credential/README.md

Okay, can you add it to your PR please?

**Comment by lalc** [comment]
> > > @lalc do you have a link to specification for the issuance protocol?
> > 
> > 
> > Here you go: https://github.com/hyperledger/aries-rfcs/blob/main/features/0036-issue-credential/README.md
> 
> Okay, can you add it to your PR please?

Done

**Review by cre8 — APPROVED** [review]

**Pull request merged**
